spring:
  profiles:
    active: ${APP_PROFILE}
  application:
    name: redirect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:redirect}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  security:
    user:
      name: ${APP_USER}
      password: ${APP_PASSWORD}
redirect:
  errorUrl: https://platformrp.ru
secrets:
  encryptionKey: ${ENCRYPTION_KEY}
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /e67d4c74-dfcd-4c24-94f9-7540d4d07f3b
      path-mapping:
        health: /check
      exposure:
        include: health
